apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: firstapp
  namespace: argocd
spec: 
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: testapp
    repoURL: "https://github.com/aneeshansaricloud/argoapp.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
      - CreateNamespace=true

    
